### ISSUE TITLE
Owner are not paying fee?

### ISSUE THREAD

**Issue by freakyy85** [RedPanda4552/SimpleEgg#2]
It looks like the staff people dont have to pay for catching? Is that a not-listed permission node?

**Comment by freakyy85** [comment]
they are op. it uses vault. i think u have it fixed. at least thats what my mail said? :D

**Comment by freakyy85** [comment]
they use admin permissions.

**Comment by RedPanda4552** [comment]
If you could, try to recreate the behavior on v0.4.2. If this behavior is on an older version then it was likely fixed.
