### ISSUE TITLE
error when player tries to catch mooshroom

### ISSUE THREAD

**Issue by A-Valk** [RedPanda4552/SimpleEgg#3]
I'm getting this error whenever someone tries to catch a mooshroom
(other mobs work fine, player has right permissions)
https://pastebin.com/rdS3CYxs

using version 0.4.2 of the plugin and current latest version of spigot
(CraftBukkit version git-Spigot-0ede7d0-ee5efeb (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT))

**Comment by RedPanda4552** [comment]
Resolved as of 0.4.3.
